# Generated by Django 4.1.4 on 2022-12-19 19:14

import birthday.fields
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=80)),
                ('photo', models.ImageField(upload_to='photos/%y/%m/%d/')),
                ('body', ckeditor.fields.RichTextField()),
                ('github_link', models.URLField(max_length=100)),
                ('linkedin_link', models.URLField(max_length=100)),
                ('instagram_link', models.URLField(max_length=100)),
                ('twitter_link', models.URLField(max_length=100)),
                ('birthday_dayofyear_internal', models.PositiveSmallIntegerField(default=None, editable=False, null=True)),
                ('birthday', birthday.fields.BirthdayField()),
            ],
        ),
    ]
