# Generated by Django 4.1.4 on 2022-12-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0002_alter_about_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='city',
            field=models.CharField(default=False, max_length=30),
        ),
        migrations.AddField(
            model_name='about',
            name='country',
            field=models.CharField(default=False, max_length=30),
        ),
        migrations.AddField(
            model_name='about',
            name='email',
            field=models.EmailField(default=False, max_length=254),
        ),
        migrations.AddField(
            model_name='about',
            name='phone',
            field=models.CharField(default=False, max_length=16),
        ),
    ]
