# Generated by Django 4.1.4 on 2022-12-20 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0004_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='css',
            new_name='percentage',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='dtl',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='html',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='javascript',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='postgresql',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='python',
        ),
    ]
