# Generated by Django 4.1.4 on 2022-12-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0005_rename_title_skill_name_rename_css_skill_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('document', models.FileField(upload_to='documents')),
            ],
        ),
    ]
