# Generated by Django 4.1.4 on 2022-12-20 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0006_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('details', models.TextField()),
                ('upload_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.AddField(
            model_name='skill',
            name='upload_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
