# Generated by Django 4.1.4 on 2022-12-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0007_service_skill_upload_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
