# Generated by Django 4.1.4 on 2022-12-22 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0009_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('photo', models.ImageField(upload_to='photos/%y/%m/%d/')),
                ('web_url', models.URLField(max_length=100)),
                ('github_url', models.URLField(max_length=100)),
            ],
        ),
    ]
