# Generated by Django 4.1.4 on 2022-12-22 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0010_portfolio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
