# Generated by Django 4.1.4 on 2022-12-22 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0011_delete_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
