# Generated by Django 4.1.4 on 2022-12-23 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0013_alter_portfolio_description_alter_service_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='background_photo',
        ),
    ]
