# Generated by Django 4.1 on 2023-06-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0014_remove_about_background_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='about_photo',
            field=models.ImageField(default=1, upload_to='photos/%y/%m/%d/'),
            preserve_default=False,
        ),
    ]
